import type { Brand, Cart, Category, Product } from './types';

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const mockCategories: Category[] = [
  { id: 1, name: 'Hardware', slug: 'hardware', is_featured: true },
  { id: 2, name: 'Perifericos', slug: 'perifericos', is_featured: true },
  { id: 3, name: 'Mobile', slug: 'mobile', is_featured: true },
  { id: 4, name: 'Gamer Pro', slug: 'gamer-pro', is_featured: true },
];

export const mockBrands: Brand[] = [
  { id: 1, name: 'NVIDIA', slug: 'nvidia' },
  { id: 2, name: 'Logitech', slug: 'logitech' },
  { id: 3, name: 'Samsung', slug: 'samsung' },
  { id: 4, name: 'Corsair', slug: 'corsair' },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'GeForce RTX 5080 Aero 16GB GDDR7',
    slug: 'geforce-rtx-5080-aero',
    sku: 'GPU-5080-AERO',
    category: mockCategories[0],
    brand: mockBrands[0],
    description: 'GPU para criadores, render 3D e jogos competitivos em alta taxa de quadros.',
    specifications: { Memoria: '16GB GDDR7', Interface: 'PCIe 5.0', Energia: '850W recomendado' },
    price: '8999.90',
    promotional_price: '8249.90',
    current_price: '8249.90',
    average_rating: '4.9',
    sold_count: 188,
    is_featured: true,
    is_new: true,
    is_best_seller: true,
    in_stock: true,
    primary_image: { id: 1, image: img('photo-1591488320449-011701bb6704'), alt_text: 'Placa de video', is_primary: true },
  },
  {
    id: 2,
    name: 'Teclado mecanico ProSwitch TKL',
    slug: 'teclado-proswitch-tkl',
    sku: 'KEY-TKL-PRO',
    category: mockCategories[1],
    brand: mockBrands[1],
    description: 'Teclado TKL com switches lineares, corpo em aluminio e baixa latencia.',
    specifications: { Layout: 'ABNT2 TKL', Switch: 'Linear', Conexao: 'USB-C' },
    price: '699.90',
    promotional_price: null,
    current_price: '699.90',
    average_rating: '4.7',
    sold_count: 94,
    is_featured: true,
    is_new: false,
    is_best_seller: true,
    in_stock: true,
    primary_image: { id: 2, image: img('photo-1587829741301-dc798b83add3'), alt_text: 'Teclado mecanico', is_primary: true },
  },
  {
    id: 3,
    name: 'SSD NVMe Gen5 2TB HeatShield',
    slug: 'ssd-nvme-gen5-2tb',
    sku: 'SSD-G5-2TB',
    category: mockCategories[0],
    brand: mockBrands[2],
    description: 'Armazenamento de alta performance para workstations e setups gamer.',
    specifications: { Leitura: '12400 MB/s', Gravacao: '11800 MB/s', Capacidade: '2TB' },
    price: '1699.90',
    promotional_price: '1399.90',
    current_price: '1399.90',
    average_rating: '4.8',
    sold_count: 73,
    is_featured: false,
    is_new: true,
    is_best_seller: false,
    in_stock: true,
    primary_image: { id: 3, image: img('photo-1597872200969-2b65d56bd16b'), alt_text: 'SSD NVMe', is_primary: true },
  },
  {
    id: 4,
    name: 'Headset Studio Gamer Wireless',
    slug: 'headset-studio-gamer-wireless',
    sku: 'AUD-WL-STUDIO',
    category: mockCategories[1],
    brand: mockBrands[3],
    description: 'Audio espacial, microfone removivel e bateria para longas sessoes.',
    specifications: { Bateria: '48h', Driver: '50mm', Conexao: '2.4GHz e Bluetooth' },
    price: '999.90',
    promotional_price: '849.90',
    current_price: '849.90',
    average_rating: '4.6',
    sold_count: 112,
    is_featured: true,
    is_new: false,
    is_best_seller: true,
    in_stock: true,
    primary_image: { id: 4, image: img('photo-1618366712010-f4ae9c647dcb'), alt_text: 'Headset gamer', is_primary: true },
  },
];

export const emptyCart: Cart = {
  id: 0,
  items: [],
  subtotal: '0.00',
  discount: '0.00',
  shipping: '0.00',
  total: '0.00',
};
